x=3
print(type(x))
z=True
print(type(z))
name="Ayman Emad Hssan"
print(name.capitalize())
print(name.title())
print(name.upper())
print(name.count("a"))
print(name.count(""))
print(len(name))
print(name[0])
print(name[-1])
print(name[12])
print(name[0:5] , name[6:13])
print(name[6:])
print(name[-7:-1])
print(name[-7:])
print(name[-1:-8:-1])
print(name.find("d"))
print(name.replace("Emad","Hassan"))
print(name.split())
x=name.split()
print(x)
print(type(x))
print(x[0])
y=" ".join(x)
print(y)
fruit=["apple","banana","grape"]
print(fruit)
fruit.append("orange")
print(fruit)
fruit.insert(1,"kiwi")
print(fruit)
fruit.remove("banana")
print(fruit)
vegetables=["tomato","cucumber","carrot"]
grocery_list=fruit.copy()
grocery_list.extend(vegetables)
print(grocery_list)
print(fruit)
ages=[2,10,12,100,34,60,56,78,8,90]
ages.sort()
print(ages)
ages.sort(reverse=True)
print(ages)
f=input("Enter your name: ")
print("Hello",f)
age=int(input("Enter your age: "))
yearof_birth=2026-age
print("Your year of birth is:", yearof_birth)
s="Time is one of the universe's greatest paradoxes: universally felt yet fundamentally misunderstood. In our daily lives, we experience it as an absolute, steady river flowing from a fixed past toward an unwritten future, a view championed by classical physics. However, Albert Einstein upended this intuition with his theories of relativity, proving that time is actually a flexible fabric interwoven with space, stretching or compressing depending on how fast you move and how much gravity you experience. While thermodynamics provides a strict arrow of time through the continuous rise of entropy and cosmic disorder, quantum mechanics complicates this further by suggesting that at the most fundamental subatomic level, the distinction between past and future completely disappears. This leaves modern science with the profound possibility that our perception of the steady ticking clock is merely a persistent human illusion, and that past, present, and future all exist simultaneously in a giant, four-dimensional block universe."
words=s.split()
print(words)
print("Number of words in your text is:",len(words))
statements=s.split(".")
print(statements)
print("Number of statements in your text is:",len(statements))